#!/bin/bash

#lib_install - Install various packages for setting up of FindnSecure version 4

selection=

#You need to be root to install packages 
if [ $(id -u) != "0" ]; then
    echo "Permission denied. Are you root?"
    exit 1
fi

#exit neatly in any situation - except for SIGKILL from outer space
trap clean_exit SIGHUP SIGINT SIGTERM

usage()
{
echo "usage: lib_install [[-h]]"
}

#rebuild packages index from sources
update_index()
{
sudo apt-get update
echo "Packages index updated.";
}

#upgrade all existing packages
upgrade_packages()
{
sudo apt-get -y upgrade
echo "Upgrade complete."
}

#install php packages
install_php_libs()
{
echo "Installing PHP packages..."
sudo apt-get install -y php5 php5-dbg php5-dev php5-common php5-recode php5-ldap php5-pspell php5-snmp php5-curl php5-xsl php5-xmlrpc php5-gmp php5-gd php5-pgsql php5-odbc php5-cli php5-sqlite php5-cgi php5-tidy libapache2-mod-php5 php5-mysql
echo "Installation of PHP packages complete."
}

#install MySQL Packages
install_mysql_libs()
{
echo "Installing MySQL packages..."
sudo apt-get install -y libdbd-mysql-perl libdbi-perl libmysqlclient-dev libmysqlclient18 librdf0 mysql-client mysql-client-5.5 mysql-client-core-5.5 mysql-common mysql-server mysql-server-5.5 mysql-server-core-5.5 rsyslog libmyodbc libmysql++-dev libmysql++3
echo "Installation of MySQL packages complete."
}

#install XRDP
install_xrdp()
{
echo "Installing XRDP..."
sudo apt-get install -y xrdp
echo "Installation of XRDP complete."
}

#install Ubuntu Desktop
install_ubuntu_desktop()
{
echo "Installing Ubuntu Desktop..."
sudo apt-get install -y ubuntu-desktop
echo "Installation of Ubuntu Desktop complete."
}

#install Screen
install_screen()
{
echo "Installing Screen..."
#change to /home directory before starting
cd $HOME

#get customized screen version and save to screenrc
wget spark-public.s3.amazonaws.com/startup/code/screenrc -O .screenrc

echo "Installation of Screen complete."
}

#install synaptic package manager
install_synaptic()
{
echo "Installing Synaptic Package Manager..."
sudo apt-get install -y synaptic
echo "Installation of Synaptic Package Manager complete."
}

#install axel
install_axel()
{
echo "Installing Axel..."
sudo apt-get install -y axel
echo "Installation of Axel complete."
}

#apply vnc license on Ubuntu, after VNC server has been installed
apply_vnc_license()
{
echo "Applying VNC License..."
vnclicense -add 6MG9J-XQNEM-MUBVR-4ZNSZ-2TMLA
}

#add Cron jobs
add_cron_jobs()
{
echo "Adding CRON jobs..."

#list CRON jobs
job_1="0 */1 * * * wget -T 0 http://127.0.0.1/php/getpage.php?mode=autoHandler"
job_2="0 0 1 * * mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -pembarc mysql"

#fetch all previous cron jobs
crontab -l > cron_dump

#add two new jobs
echo $job_1 >> cron_dump
echo $job_2 >> cron_dump

#add all jobs to crontab
crontab cron_dump
echo "CRON jobs added successfully."
}

#exit program neatly - exit housekeeping
clean_exit()
{
if [ -f "cron_dump" ]; then
rm -f cron_dump
fi
exit 0
}

while [ "$1" != "" ]; do
case $1 in
-h | --help ) usage; exit;;
esac
shift
done

until [ "$selection" = "0" ]; do
echo "
1 - Update Packages Index
2 - Upgrade Packages
3 - Install PHP Packages
4 - Install MySQL Packages
5 - Install XRDP
6 - Install Ubuntu Desktop
7 - Install Screen
8 - Install Synaptic Package Manager
9 - Install Axel
10 - Apply VNC License
11 - Add CRON Jobs
0 - Exit
"
echo -n "Enter Selection: "
read selection
echo ""

case $selection in
1 ) update_index ;;
2 ) upgrade_packages ;;
3 ) install_php_libs ;;
4 ) install_mysql_libs ;;
5 ) install_xrdp ;;
6 ) install_ubuntu_desktop ;;
7 ) install_screen ;;
8 ) install_synaptic ;;
9 ) install_axel ;;
10 ) apply_vnc_license ;;
11 ) add_cron_jobs ;;
0 ) clean_exit ;;
* ) echo "Invalid Input";
esac
done
